SELECT FPLAYER.PLAYER_NAME, FPLAYER.PLAYER_SALARY, FTROPHY.TROPHY_YEAR
FROM FPLAYER
WHERE NOT EXISTS
    (SELECT *
    FROM FWINS
    WHERE NOT EXISTS
        (SELECT *
        FROM FTROPHY
        WHERE FPLAYER.PLAYERID = FWINS.PLAYERID
        AND FWINS.TROPHYID = FTROPHY.TROPHYID
        AND FTROPHY.TROPHY_NAME = "Ballon d'Or"));