CREATE OR REPLACE VIEW FINQUERY1 AS
SELECT FTROPHY.TROPHY_NAME, FTROPHY.TROPHY_YEAR
FROM FTROPHY 
WHERE NOT EXISTS
    (SELECT *
    FROM FNATIONALTEAM
    WHERE FNATIONALTEAM.NAT_NAME = 'Brazil'
    AND NOT EXISTS
        (SELECT *
        FROM FWINS
        WHERE FTROPHY.TROPHYID = FWINS.TROPHYID
        AND FWINS.NATID = FNATIONALTEAM.NATID));