CREATE OR REPLACE VIEW FINQUERY7 AS
SELECT FPRODUCTS.PRODUCT_PRICE, FTOURNAMENT.TOURN_ASSOC, FLEAGUE.LEAGUE_REGION,FCLUBTEAM.CLUB_NAME, FNATIONALTEAM.NAT_NAME
FROM FPRODUCTS, FPRODUCEDBY, FCLUBTEAM, FNATIONALTEAM, FLEAGUE, FTOURNAMENT
WHERE FPRODUCTS.PRODUCTID = FPRODUCEDBY.PRODUCTID
AND FPRODUCEDBY.CLUBID = FCLUBTEAM.CLUBID
AND FPRODUCEDBY.NATID = FNATIONALTEAM.NATID
AND FPRODUCEDBY.TOURNAMENTID = FTOURNAMENT.TOURNAMENTID
AND FPRODUCEDBY.LEAGUEID = FLEAGUE.LEAGUEID
AND FPRODUCTS.PRODUCT_TYPE = 'Event';