CREATE OR REPLACE VIEW FINQUERY6 AS
SELECT FNATIONALTEAM.NAT_NAME, FTROPHY.TROPHY_NAME, FTROPHY.TROPHYID
FROM FTROPHY FULL JOIN FWINS
ON FTROPHY.TROPHYID = FWINS.TROPHYID
FULL JOIN FNATIONALTEAM
ON FWINS.NATID = FNATIONALTEAM.NATID
ORDER BY FNATIONALTEAM.NAT_NAME;