CREATE OR REPLACE VIEW FINQUERY2 AS 
SELECT FNATIONALTEAM.NAT_NAME
FROM FNATIONALTEAM
WHERE FNATIONALTEAM.NATID NOT IN
    (SELECT FPRODUCEDBY.NATID
    FROM FPRODUCEDBY
    WHERE FPRODUCEDBY.PRODUCTID NOT IN
        (SELECT FPRODUCTS.PRODUCTID
        FROM FPRODUCTS
        WHERE FPRODUCTS.PRODUCT_TYPE = 'Event'));