SELECT FNATIONALTEAM.NAT_NAME
FROM FNATIONALTEAM
WHERE FNATIONALTEAM.NATID NOT IN
    (SELECT FPRODUCEBY.NATID
    FROM FPRODUCEDBY
    WHERE FPRODUCEDBY.PRODUCTID NOT IN
        (SELECT FPRODUCT.PRODUCTID
        FROM FPRODUCT
        WHERE FPRODUCT.PRODCUT_TYPE = 'clothing'));